/*
 * JOCLBlast - Java bindings for CLBlast
 *
 * Copyright (c) 2015-2017 Marco Hutter - http://www.jocl.org
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jocl_blast_CLBlast */

#ifndef _Included_org_jocl_blast_CLBlast
#define _Included_org_jocl_blast_CLBlast
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jocl_blast_CLBlast_JOCL_BLAST_STATUS_INTERNAL_ERROR
#define org_jocl_blast_CLBlast_JOCL_BLAST_STATUS_INTERNAL_ERROR -32786L
/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    setLogLevelNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jocl_blast_CLBlast_setLogLevelNative
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastSrotgNative
 * Signature: (Lorg/jocl/cl_mem;JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastSrotgNative
  (JNIEnv *, jclass, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDrotgNative
 * Signature: (Lorg/jocl/cl_mem;JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDrotgNative
  (JNIEnv *, jclass, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastSrotmgNative
 * Signature: (Lorg/jocl/cl_mem;JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastSrotmgNative
  (JNIEnv *, jclass, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDrotmgNative
 * Signature: (Lorg/jocl/cl_mem;JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDrotmgNative
  (JNIEnv *, jclass, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastSrotNative
 * Signature: (JLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJFFLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastSrotNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jfloat, jfloat, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDrotNative
 * Signature: (JLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJDDLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDrotNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jdouble, jdouble, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastSrotmNative
 * Signature: (JLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastSrotmNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDrotmNative
 * Signature: (JLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDrotmNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastSswapNative
 * Signature: (JLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastSswapNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDswapNative
 * Signature: (JLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDswapNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastCswapNative
 * Signature: (JLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastCswapNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZswapNative
 * Signature: (JLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZswapNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastSscalNative
 * Signature: (JFLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastSscalNative
  (JNIEnv *, jclass, jlong, jfloat, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDscalNative
 * Signature: (JDLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDscalNative
  (JNIEnv *, jclass, jlong, jdouble, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastCscalNative
 * Signature: (J[FLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastCscalNative
  (JNIEnv *, jclass, jlong, jfloatArray, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZscalNative
 * Signature: (J[DLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZscalNative
  (JNIEnv *, jclass, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastScopyNative
 * Signature: (JLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastScopyNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDcopyNative
 * Signature: (JLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDcopyNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastCcopyNative
 * Signature: (JLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastCcopyNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZcopyNative
 * Signature: (JLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZcopyNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastSaxpyNative
 * Signature: (JFLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastSaxpyNative
  (JNIEnv *, jclass, jlong, jfloat, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDaxpyNative
 * Signature: (JDLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDaxpyNative
  (JNIEnv *, jclass, jlong, jdouble, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastCaxpyNative
 * Signature: (J[FLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastCaxpyNative
  (JNIEnv *, jclass, jlong, jfloatArray, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZaxpyNative
 * Signature: (J[DLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZaxpyNative
  (JNIEnv *, jclass, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastSdotNative
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastSdotNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDdotNative
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDdotNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastCdotuNative
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastCdotuNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZdotuNative
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZdotuNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastCdotcNative
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastCdotcNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZdotcNative
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZdotcNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastSnrm2Native
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastSnrm2Native
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDnrm2Native
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDnrm2Native
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastScnrm2Native
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastScnrm2Native
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDznrm2Native
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDznrm2Native
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastSasumNative
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastSasumNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDasumNative
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDasumNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastScasumNative
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastScasumNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDzasumNative
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDzasumNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastSsumNative
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastSsumNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDsumNative
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDsumNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastScsumNative
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastScsumNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDzsumNative
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDzsumNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastiSamaxNative
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastiSamaxNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastiDamaxNative
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastiDamaxNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastiCamaxNative
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastiCamaxNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastiZamaxNative
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastiZamaxNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastiSaminNative
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastiSaminNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastiDaminNative
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastiDaminNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastiCaminNative
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastiCaminNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastiZaminNative
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastiZaminNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastiSmaxNative
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastiSmaxNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastiDmaxNative
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastiDmaxNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastiCmaxNative
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastiCmaxNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastiZmaxNative
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastiZmaxNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastiSminNative
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastiSminNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastiDminNative
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastiDminNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastiCminNative
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastiCminNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastiZminNative
 * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastiZminNative
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastSgemvNative
 * Signature: (IIJJFLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJFLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastSgemvNative
  (JNIEnv *, jclass, jint, jint, jlong, jlong, jfloat, jobject, jlong, jlong, jobject, jlong, jlong, jfloat, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDgemvNative
 * Signature: (IIJJDLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJDLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDgemvNative
  (JNIEnv *, jclass, jint, jint, jlong, jlong, jdouble, jobject, jlong, jlong, jobject, jlong, jlong, jdouble, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastCgemvNative
 * Signature: (IIJJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastCgemvNative
  (JNIEnv *, jclass, jint, jint, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZgemvNative
 * Signature: (IIJJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZgemvNative
  (JNIEnv *, jclass, jint, jint, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastSgbmvNative
 * Signature: (IIJJJJFLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJFLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastSgbmvNative
  (JNIEnv *, jclass, jint, jint, jlong, jlong, jlong, jlong, jfloat, jobject, jlong, jlong, jobject, jlong, jlong, jfloat, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDgbmvNative
 * Signature: (IIJJJJDLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJDLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDgbmvNative
  (JNIEnv *, jclass, jint, jint, jlong, jlong, jlong, jlong, jdouble, jobject, jlong, jlong, jobject, jlong, jlong, jdouble, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastCgbmvNative
 * Signature: (IIJJJJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastCgbmvNative
  (JNIEnv *, jclass, jint, jint, jlong, jlong, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZgbmvNative
 * Signature: (IIJJJJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZgbmvNative
  (JNIEnv *, jclass, jint, jint, jlong, jlong, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastChemvNative
 * Signature: (IIJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastChemvNative
  (JNIEnv *, jclass, jint, jint, jlong, jfloatArray, jobject, jlong, jlong, jobject, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZhemvNative
 * Signature: (IIJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZhemvNative
  (JNIEnv *, jclass, jint, jint, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastChbmvNative
 * Signature: (IIJJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastChbmvNative
  (JNIEnv *, jclass, jint, jint, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZhbmvNative
 * Signature: (IIJJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZhbmvNative
  (JNIEnv *, jclass, jint, jint, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastChpmvNative
 * Signature: (IIJ[FLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastChpmvNative
  (JNIEnv *, jclass, jint, jint, jlong, jfloatArray, jobject, jlong, jobject, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZhpmvNative
 * Signature: (IIJ[DLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZhpmvNative
  (JNIEnv *, jclass, jint, jint, jlong, jdoubleArray, jobject, jlong, jobject, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastSsymvNative
 * Signature: (IIJFLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJFLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastSsymvNative
  (JNIEnv *, jclass, jint, jint, jlong, jfloat, jobject, jlong, jlong, jobject, jlong, jlong, jfloat, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDsymvNative
 * Signature: (IIJDLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJDLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDsymvNative
  (JNIEnv *, jclass, jint, jint, jlong, jdouble, jobject, jlong, jlong, jobject, jlong, jlong, jdouble, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastSsbmvNative
 * Signature: (IIJJFLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJFLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastSsbmvNative
  (JNIEnv *, jclass, jint, jint, jlong, jlong, jfloat, jobject, jlong, jlong, jobject, jlong, jlong, jfloat, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDsbmvNative
 * Signature: (IIJJDLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJDLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDsbmvNative
  (JNIEnv *, jclass, jint, jint, jlong, jlong, jdouble, jobject, jlong, jlong, jobject, jlong, jlong, jdouble, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastSspmvNative
 * Signature: (IIJFLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJFLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastSspmvNative
  (JNIEnv *, jclass, jint, jint, jlong, jfloat, jobject, jlong, jobject, jlong, jlong, jfloat, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDspmvNative
 * Signature: (IIJDLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJDLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDspmvNative
  (JNIEnv *, jclass, jint, jint, jlong, jdouble, jobject, jlong, jobject, jlong, jlong, jdouble, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastStrmvNative
 * Signature: (IIIIJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastStrmvNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDtrmvNative
 * Signature: (IIIIJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDtrmvNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastCtrmvNative
 * Signature: (IIIIJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastCtrmvNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZtrmvNative
 * Signature: (IIIIJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZtrmvNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastStbmvNative
 * Signature: (IIIIJJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastStbmvNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDtbmvNative
 * Signature: (IIIIJJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDtbmvNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastCtbmvNative
 * Signature: (IIIIJJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastCtbmvNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZtbmvNative
 * Signature: (IIIIJJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZtbmvNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastStpmvNative
 * Signature: (IIIIJLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastStpmvNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDtpmvNative
 * Signature: (IIIIJLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDtpmvNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastCtpmvNative
 * Signature: (IIIIJLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastCtpmvNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZtpmvNative
 * Signature: (IIIIJLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZtpmvNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastStrsvNative
 * Signature: (IIIIJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastStrsvNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDtrsvNative
 * Signature: (IIIIJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDtrsvNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastCtrsvNative
 * Signature: (IIIIJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastCtrsvNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZtrsvNative
 * Signature: (IIIIJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZtrsvNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastStbsvNative
 * Signature: (IIIIJJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastStbsvNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDtbsvNative
 * Signature: (IIIIJJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDtbsvNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastCtbsvNative
 * Signature: (IIIIJJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastCtbsvNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZtbsvNative
 * Signature: (IIIIJJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZtbsvNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastStpsvNative
 * Signature: (IIIIJLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastStpsvNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDtpsvNative
 * Signature: (IIIIJLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDtpsvNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastCtpsvNative
 * Signature: (IIIIJLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastCtpsvNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZtpsvNative
 * Signature: (IIIIJLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZtpsvNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastSgerNative
 * Signature: (IJJFLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastSgerNative
  (JNIEnv *, jclass, jint, jlong, jlong, jfloat, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDgerNative
 * Signature: (IJJDLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDgerNative
  (JNIEnv *, jclass, jint, jlong, jlong, jdouble, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastCgeruNative
 * Signature: (IJJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastCgeruNative
  (JNIEnv *, jclass, jint, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZgeruNative
 * Signature: (IJJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZgeruNative
  (JNIEnv *, jclass, jint, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastCgercNative
 * Signature: (IJJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastCgercNative
  (JNIEnv *, jclass, jint, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZgercNative
 * Signature: (IJJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZgercNative
  (JNIEnv *, jclass, jint, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastCherNative
 * Signature: (IIJFLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastCherNative
  (JNIEnv *, jclass, jint, jint, jlong, jfloat, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZherNative
 * Signature: (IIJDLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZherNative
  (JNIEnv *, jclass, jint, jint, jlong, jdouble, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastChprNative
 * Signature: (IIJFLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastChprNative
  (JNIEnv *, jclass, jint, jint, jlong, jfloat, jobject, jlong, jlong, jobject, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZhprNative
 * Signature: (IIJDLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZhprNative
  (JNIEnv *, jclass, jint, jint, jlong, jdouble, jobject, jlong, jlong, jobject, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastCher2Native
 * Signature: (IIJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastCher2Native
  (JNIEnv *, jclass, jint, jint, jlong, jfloatArray, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZher2Native
 * Signature: (IIJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZher2Native
  (JNIEnv *, jclass, jint, jint, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastChpr2Native
 * Signature: (IIJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastChpr2Native
  (JNIEnv *, jclass, jint, jint, jlong, jfloatArray, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZhpr2Native
 * Signature: (IIJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZhpr2Native
  (JNIEnv *, jclass, jint, jint, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastSsyrNative
 * Signature: (IIJFLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastSsyrNative
  (JNIEnv *, jclass, jint, jint, jlong, jfloat, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDsyrNative
 * Signature: (IIJDLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDsyrNative
  (JNIEnv *, jclass, jint, jint, jlong, jdouble, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastSsprNative
 * Signature: (IIJFLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastSsprNative
  (JNIEnv *, jclass, jint, jint, jlong, jfloat, jobject, jlong, jlong, jobject, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDsprNative
 * Signature: (IIJDLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDsprNative
  (JNIEnv *, jclass, jint, jint, jlong, jdouble, jobject, jlong, jlong, jobject, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastSsyr2Native
 * Signature: (IIJFLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastSsyr2Native
  (JNIEnv *, jclass, jint, jint, jlong, jfloat, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDsyr2Native
 * Signature: (IIJDLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDsyr2Native
  (JNIEnv *, jclass, jint, jint, jlong, jdouble, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastSspr2Native
 * Signature: (IIJFLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastSspr2Native
  (JNIEnv *, jclass, jint, jint, jlong, jfloat, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDspr2Native
 * Signature: (IIJDLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDspr2Native
  (JNIEnv *, jclass, jint, jint, jlong, jdouble, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastSgemmNative
 * Signature: (IIIJJJFLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJFLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastSgemmNative
  (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jlong, jfloat, jobject, jlong, jlong, jobject, jlong, jlong, jfloat, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDgemmNative
 * Signature: (IIIJJJDLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJDLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDgemmNative
  (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jlong, jdouble, jobject, jlong, jlong, jobject, jlong, jlong, jdouble, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastCgemmNative
 * Signature: (IIIJJJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastCgemmNative
  (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZgemmNative
 * Signature: (IIIJJJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZgemmNative
  (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastSsymmNative
 * Signature: (IIIJJFLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJFLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastSsymmNative
  (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jfloat, jobject, jlong, jlong, jobject, jlong, jlong, jfloat, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDsymmNative
 * Signature: (IIIJJDLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJDLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDsymmNative
  (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jdouble, jobject, jlong, jlong, jobject, jlong, jlong, jdouble, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastCsymmNative
 * Signature: (IIIJJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastCsymmNative
  (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZsymmNative
 * Signature: (IIIJJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZsymmNative
  (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastChemmNative
 * Signature: (IIIJJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastChemmNative
  (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZhemmNative
 * Signature: (IIIJJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZhemmNative
  (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastSsyrkNative
 * Signature: (IIIJJFLorg/jocl/cl_mem;JJFLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastSsyrkNative
  (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jfloat, jobject, jlong, jlong, jfloat, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDsyrkNative
 * Signature: (IIIJJDLorg/jocl/cl_mem;JJDLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDsyrkNative
  (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jdouble, jobject, jlong, jlong, jdouble, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastCsyrkNative
 * Signature: (IIIJJ[FLorg/jocl/cl_mem;JJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastCsyrkNative
  (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jfloatArray, jobject, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZsyrkNative
 * Signature: (IIIJJ[DLorg/jocl/cl_mem;JJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZsyrkNative
  (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastCherkNative
 * Signature: (IIIJJFLorg/jocl/cl_mem;JJFLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastCherkNative
  (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jfloat, jobject, jlong, jlong, jfloat, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZherkNative
 * Signature: (IIIJJDLorg/jocl/cl_mem;JJDLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZherkNative
  (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jdouble, jobject, jlong, jlong, jdouble, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastSsyr2kNative
 * Signature: (IIIJJFLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJFLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastSsyr2kNative
  (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jfloat, jobject, jlong, jlong, jobject, jlong, jlong, jfloat, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDsyr2kNative
 * Signature: (IIIJJDLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJDLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDsyr2kNative
  (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jdouble, jobject, jlong, jlong, jobject, jlong, jlong, jdouble, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastCsyr2kNative
 * Signature: (IIIJJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastCsyr2kNative
  (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZsyr2kNative
 * Signature: (IIIJJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZsyr2kNative
  (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastCher2kNative
 * Signature: (IIIJJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJFLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastCher2kNative
  (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jlong, jlong, jfloat, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZher2kNative
 * Signature: (IIIJJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJDLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZher2kNative
  (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jlong, jlong, jdouble, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastStrmmNative
 * Signature: (IIIIIJJFLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastStrmmNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jlong, jlong, jfloat, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDtrmmNative
 * Signature: (IIIIIJJDLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDtrmmNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jlong, jlong, jdouble, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastCtrmmNative
 * Signature: (IIIIIJJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastCtrmmNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZtrmmNative
 * Signature: (IIIIIJJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZtrmmNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastStrsmNative
 * Signature: (IIIIIJJFLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastStrsmNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jlong, jlong, jfloat, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDtrsmNative
 * Signature: (IIIIIJJDLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDtrsmNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jlong, jlong, jdouble, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastCtrsmNative
 * Signature: (IIIIIJJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastCtrsmNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZtrsmNative
 * Signature: (IIIIIJJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZtrsmNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastSomatcopyNative
 * Signature: (IIJJFLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastSomatcopyNative
  (JNIEnv *, jclass, jint, jint, jlong, jlong, jfloat, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDomatcopyNative
 * Signature: (IIJJDLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDomatcopyNative
  (JNIEnv *, jclass, jint, jint, jlong, jlong, jdouble, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastComatcopyNative
 * Signature: (IIJJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastComatcopyNative
  (JNIEnv *, jclass, jint, jint, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZomatcopyNative
 * Signature: (IIJJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZomatcopyNative
  (JNIEnv *, jclass, jint, jint, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastSaxpyBatchedNative
 * Signature: (J[FLorg/jocl/cl_mem;[JJLorg/jocl/cl_mem;[JJJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastSaxpyBatchedNative
  (JNIEnv *, jclass, jlong, jfloatArray, jobject, jlongArray, jlong, jobject, jlongArray, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDaxpyBatchedNative
 * Signature: (J[DLorg/jocl/cl_mem;[JJLorg/jocl/cl_mem;[JJJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDaxpyBatchedNative
  (JNIEnv *, jclass, jlong, jdoubleArray, jobject, jlongArray, jlong, jobject, jlongArray, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastCaxpyBatchedNative
 * Signature: (J[FLorg/jocl/cl_mem;[JJLorg/jocl/cl_mem;[JJJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastCaxpyBatchedNative
  (JNIEnv *, jclass, jlong, jfloatArray, jobject, jlongArray, jlong, jobject, jlongArray, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZaxpyBatchedNative
 * Signature: (J[DLorg/jocl/cl_mem;[JJLorg/jocl/cl_mem;[JJJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZaxpyBatchedNative
  (JNIEnv *, jclass, jlong, jdoubleArray, jobject, jlongArray, jlong, jobject, jlongArray, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastSgemmBatchedNative
 * Signature: (IIIJJJ[FLorg/jocl/cl_mem;[JJLorg/jocl/cl_mem;[JJ[FLorg/jocl/cl_mem;[JJJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastSgemmBatchedNative
  (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jlong, jfloatArray, jobject, jlongArray, jlong, jobject, jlongArray, jlong, jfloatArray, jobject, jlongArray, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastDgemmBatchedNative
 * Signature: (IIIJJJ[DLorg/jocl/cl_mem;[JJLorg/jocl/cl_mem;[JJ[DLorg/jocl/cl_mem;[JJJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastDgemmBatchedNative
  (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jlong, jdoubleArray, jobject, jlongArray, jlong, jobject, jlongArray, jlong, jdoubleArray, jobject, jlongArray, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastCgemmBatchedNative
 * Signature: (IIIJJJ[FLorg/jocl/cl_mem;[JJLorg/jocl/cl_mem;[JJ[FLorg/jocl/cl_mem;[JJJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastCgemmBatchedNative
  (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jlong, jfloatArray, jobject, jlongArray, jlong, jobject, jlongArray, jlong, jfloatArray, jobject, jlongArray, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastZgemmBatchedNative
 * Signature: (IIIJJJ[DLorg/jocl/cl_mem;[JJLorg/jocl/cl_mem;[JJ[DLorg/jocl/cl_mem;[JJJLorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastZgemmBatchedNative
  (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jlong, jdoubleArray, jobject, jlongArray, jlong, jobject, jlongArray, jlong, jdoubleArray, jobject, jlongArray, jlong, jlong, jobject, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastClearCacheNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastClearCacheNative
  (JNIEnv *, jclass);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastFillCacheNative
 * Signature: (Lorg/jocl/cl_device_id;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastFillCacheNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jocl_blast_CLBlast
 * Method:    CLBlastOverrideParametersNative
 * Signature: (Lorg/jocl/cl_device_id;Ljava/lang/String;IJ[Ljava/lang/String;[J)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_blast_CLBlast_CLBlastOverrideParametersNative
  (JNIEnv *, jclass, jobject, jstring, jint, jlong, jobjectArray, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
